package src.main.java.org.Dec13.Homework;

public class Question52 {

}


/*
 *
 52- Write a method that returns the sum of all even Fibonacci numbers. Consider all Fibonacci numbers that are less than or equal to n.
 Each new element in the Fibonacci sequence is generated by adding the previous two elements.
 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

 */